<?php
namespace App\Services;

use PDO;
use App\Services\GdlCodeGeneratorService;

class LocalExportService
{
    private $db;

    public function __construct(PDO $db)
    {
        $this->db = $db;
    }

    /**
     * Export database object back to filesystem
     */
    public function exportObjectToFiles($objectId)
    {
        // Get object details
        $stmt = $this->db->prepare("SELECT * FROM gdl_objects WHERE id = ? OR local_file_path = ?");
        $stmt->execute([$objectId, $objectId]);
        $object = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$object) {
            // Check if it's a direct path and exists
            if (is_dir($objectId)) {
                throw new \Exception("Object exists on disk but not in database. Please import first: $objectId");
            }
            throw new \Exception("Object not found in database: $objectId");
        }

        if (!$object['is_local_sync'] || !$object['local_file_path']) {
            throw new \Exception("Object is not synced with local files");
        }

        $objectPath = $object['local_file_path'];

        if (!is_dir($objectPath)) {
            throw new \Exception("Object path not found: $objectPath");
        }

        // Export parameters to XML
        $this->exportParametersXml($objectId, $objectPath);

        // Export all scripts (merging into existing files)
        $this->exportScripts($objectId, $objectPath, $object);

        // Update sync time
        $stmt = $this->db->prepare("UPDATE gdl_objects SET last_sync_time = NOW() WHERE id = ?");
        $stmt->execute([$objectId]);

        return true;
    }

    private function exportParametersXml($objectId, $objectPath)
    {
        $xmlService = new GdlXmlService($this->db);
        $xml = $xmlService->generateParametersXml((int) $objectId);

        $xmlPath = $objectPath . '/Parameters.xml';
        file_put_contents($xmlPath, $xml);
    }

    private function mergeScript($filePath, $newContent, $header = "! --- GENERATED BY GDL-UI-STUDIO ---", $footer = "! --- END ---")
    {
        $scriptService = new GdlScriptService();
        $existingContent = file_exists($filePath) ? file_get_contents($filePath) : "";
        $newFileContent = $scriptService->mergeContent($existingContent, $newContent, $header, $footer);
        return file_put_contents($filePath, $newFileContent);
    }

    private function exportScripts($objectId, $objectPath, $object)
    {
        $generator = new GdlCodeGeneratorService();
        $scriptService = new GdlScriptService();

        $scriptFiles = [
            'script_master' => ['filename' => '1-Master-Script.gdl', 'label' => 'MASTER'],
            'script_parameter' => ['filename' => '2-Parameter-Script.gdl', 'label' => 'PARAMETER'],
            'script_2d' => ['filename' => '3-2D-Script.gdl', 'label' => '2D'],
            'script_3d' => ['filename' => '4-3D-Script.gdl', 'label' => '3D'],
            'script_ui' => ['filename' => '5-Interface-Script.gdl', 'label' => 'UI'],
            'script_properties' => ['filename' => '6-Properties-Script.gdl', 'label' => 'PROPERTIES'],
            'script_forward_migration' => ['filename' => '7-Forward-Script.gdl', 'label' => 'MIGRATION'],
            'script_backward_migration' => ['filename' => '8-Backward-Script.gdl', 'label' => 'MIGRATION']
        ];

        $notes = "Exported via GDL-UI-Studio";
        $parametersChanged = false;

        $parameters = null;

        foreach ($scriptFiles as $columnName => $config) {
            $filename = $config['filename'];
            $label = $config['label'];
            $filePath = $objectPath . '/' . $filename;

            $dbScript = trim($object[$columnName] ?? '');

            // Determine if we have anything to export
            $hasDbContent = !empty($dbScript);
            $hasAutoArrays = false;
            $hasAutoValues = false;

            if ($label === 'MASTER') {
                if ($parameters === null) {
                    $stmt = $this->db->prepare("SELECT * FROM parameters WHERE gdl_object_id = ? ORDER BY sort_order");
                    $stmt->execute([$objectId]);
                    $parameters = $stmt->fetchAll(PDO::FETCH_ASSOC);
                }
                $masterArrays = $generator->generateMasterArrays($parameters);
                $hasAutoArrays = !empty($masterArrays);
            } elseif ($label === 'PARAMETER') {
                if ($parameters === null) {
                    $stmt = $this->db->prepare("SELECT * FROM parameters WHERE gdl_object_id = ? ORDER BY sort_order");
                    $stmt->execute([$objectId]);
                    $parameters = $stmt->fetchAll(PDO::FETCH_ASSOC);
                }
                $valuesCode = $generator->generateValuesCommands($parameters);
                $hasAutoValues = !empty($valuesCode);
            }

            // Rule: No real content, no touch
            if (!$hasAutoArrays && !$hasAutoValues && $scriptService->isPlaceholderContent($dbScript)) {
                continue;
            }

            // If file doesn't exist but we have content, create it with a basic template
            if (!file_exists($filePath)) {
                if ($hasDbContent || $hasAutoArrays || $hasAutoValues) {
                    // Create new file with basic structure
                    $existingContent = "! ============================================\n";
                    $existingContent .= "! " . strtoupper($filename) . "\n";
                    $existingContent .= "! ============================================\n";
                    $existingContent .= "\n";
                    $existingContent .= "! --- START ---\n";
                    $existingContent .= "\n";
                    $existingContent .= "! --- END ---\n";
                } else {
                    // No content to export, skip file creation
                    continue;
                }
            } else {
                $existingContent = file_get_contents($filePath);
            }

            // For MASTER, PARAMETER, and UI the DB already holds the full merged file content
            // (written by LocalController). Write it directly as the base – no additional wrapper.
            // For other scripts (2D, 3D, …) the DB holds user-edited content; also write directly.
            $newContent = $hasDbContent ? $dbScript : $existingContent;

            // 1. DO NOT touch headers (Rule 1)

            // 2. Auto-generated parts using FIXED (non-timestamped) markers so that
            //    LocalController and LocalExportService always agree on the header string.
            if ($hasAutoArrays && $label === 'MASTER') {
                $newContent = $scriptService->mergeContent($newContent, $masterArrays, "! --- AUTO GENERATED ARRAYS ---", "! --- END ARRAYS ---");
                if (!$parametersChanged) {
                    $notes = "VALUES{2} Arrays created/updated";
                    $parametersChanged = true;
                }
            } elseif ($hasAutoValues && $label === 'PARAMETER') {
                $newContent = $scriptService->mergeContent($newContent, $valuesCode, "! --- AUTO GENERATED VALUES ---", "! --- END VALUES ---");
            }

            // 4. Add Release Note (Rule 3 - above END)
            $newContent = $scriptService->addReleaseNote($newContent, $notes);

            // Save if content changed OR if file doesn't exist yet (new file creation)
            if ($newContent !== $existingContent || !file_exists($filePath)) {
                file_put_contents($filePath, $newContent);
            }
        }
    }

    /**
     * Export ui_code data to ui.json
     */
    public function exportUiConfig($objectId, $objectPath)
    {
        // Get all parameters with ui_code
        $stmt = $this->db->prepare("
            SELECT id, gdl_name, ui_code
            FROM parameters
            WHERE gdl_object_id = ? AND ui_code IS NOT NULL
        ");
        $stmt->execute([$objectId]);
        $parameters = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $uiData = [
            'parameters' => []
        ];

        foreach ($parameters as $param) {
            $uiData['parameters'][] = [
                'id' => $param['id'],
                'name' => $param['gdl_name'],
                'ui_code' => $param['ui_code']
            ];
        }

        $uiJsonPath = $objectPath . '/ui.json';
        file_put_contents($uiJsonPath, json_encode($uiData, JSON_PRETTY_PRINT));
    }
}
